### ISSUE TITLE
Wire up signup flow submission

### ISSUE THREAD

**Issue by alex** [kpenning/peoplepower#5]
Can either use the ActionKit API or a pre-made widget.

Should submit the data without triggering a full page reload, and give the user a thank you message.

**Comment by liyanchang** [comment]
Samantha as a quick mock of what the javascript might look like. After you wire up and if you have time, I might suggest we look at using an older version of jquery (https://jquery.com/browser-support/ suggest jquery 1.12 which as long as it has .post helpers, should be more than enough for our purpose) so that we can support IE 8.

**Comment by alex** [comment]
This is subsumed by #26
